### ISSUE TITLE
Version mismatch: react-native: 0.56.0 => 0.59.8

### ISSUE THREAD

**Issue by yjkimjunior** [blockstack/blockstack-react-native#14]
build.gradle expects react-native v0.56.0 whereas package.json specifies v0.59.8 and causes app the crash on `react-native run-android`. 

Fix: update build.grade to expect 0.59.8, (or in general, make sure they match).

**Comment by friedger** [comment]
Fixed by https://github.com/blockstack/blockstack-react-native/pull/16/commits/159f65e109090fa50c235e432f1aab3978335490
