### ISSUE TITLE
Cannot build example or use npm package

### ISSUE THREAD

**Issue by Nfinger** [blockstack/blockstack-react-native#18]
Off of a fresh clone, after the npm install and the pod install, when I try and run the project I get the following error. Please advise

![image](https://user-images.githubusercontent.com/17767789/61159434-07a34380-a4ca-11e9-9c8c-52f1fe79ca86.png)

**Comment by shreyasthiagaraj** [comment]
@Nfinger I've updated the version on cocoapods--please try again! Let me know if you have any issues :).
