### ISSUE TITLE
I seem to have trouble using RNBlockstackSdk for RN 0.60.5. 

### ISSUE THREAD

**Issue by codeoholic** [blockstack/blockstack-react-native#19]
Since the pod file already exists, I am unable to install.
I get this error.
[!] CocoaPods could not find compatible versions for pod "Blockstack":
  In Podfile:
    Blockstack

Specs satisfying the `Blockstack` dependency were found, but they required a higher minimum deployment target.

**Comment by shreyasthiagaraj** [comment]
You must update the minimum version requirement at the top of your pod file to `11.0` from whatever it is. I believe by default it is `9.0`.

**Comment by shreyasthiagaraj** [comment]
Hey! closing this for now. If you're still having this issue, please reopen.
