### ISSUE TITLE
Build Error - Cannot convert value of type 'String' to expected argument type 'URL'

### ISSUE THREAD

**Issue by botoberich** [blockstack/blockstack-react-native#20]
![Screen Shot 2019-09-23 at 4 25 10 PM](https://user-images.githubusercontent.com/53358572/65470168-e55d6880-de1e-11e9-8c94-0b38ca497257.png)

Steps to Repro
- Clone repo
- cd example/ios
- pod install
- react-native run-ios

**Comment by shreyasthiagaraj** [comment]
This has been fixed--please do `npm update` and try again!

**Comment by shreyasthiagaraj** [comment]
1. npm update
2. Delete podfile.lock, then Pods folder, then do `pod install`
3. Clean + Build.

I believe this should fix your issue. Closing this for now, please reopen if it persists!
