### ISSUE TITLE
error: 'fromString' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by devdotmohit** [blockstack/blockstack-react-native#24]
let scopes = (config["scopes"] as? [String] ?? ["store_write"]).compactMap { AuthScope.fromString($0) }
<unknown>:0: note: 'fromString' declared here

** BUILD FAILED **

**Comment by FrankyHo** [comment]
+1

**Comment by FrankyHo** [comment]
@codeoholic , try pod update, check podfile.lock Blockstack update to 1.0.1

**Comment by shreyasthiagaraj** [comment]
@FrankyHo +1. Thanks for responding! @codeoholic you can delete podfile.lock, then pods folder, then do `pod install`.
